### ISSUE TITLE
Move from featurebook to cucumber.js

### ISSUE THREAD

**Issue by danalexilewis** [valueflows/resourceful#4]
Since starting this project cucumber.js has become much more of a thing and looks to do what is needed better :) So lets migrate.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/resourceful/-/issues/4.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
