### ISSUE TITLE
Explain my evolving methodology.

### ISSUE THREAD

**Issue by danalexilewis** [valueflows/resourceful#5]
I have been thinking about spec writing for a long time. In this project I tried to both do a Domain Driven Design/Development to define all the requirements of the app. Along the way I came up with a different approach to organising/rationalising the specs.

It goes a little something like this:
- Define an event. (gherkin: when)
- Define the conditions that could precipitate the event. (gherkin: givens)
- Define the consequences for each of the scenarios. (gherkin: thans)

Note: 
- There is only one event (When) per scenario. Ands/Buts are used to define validation criteria at the event occurrence. eg

```
Given I am an Anonymous User
When I send my New Account data
But my user name is already taken
Than I receive a helpful error message "Username taken :("
```
- And works well for conditions. But doesn't make sense... (thoughts)

```
Given I am an Anonymous User
And I have a shopping cart cookie
When I load any page
Than my cart is populated with its last items
```
- And & But can be used successfully for consequences

```
Given I am an Anonymous User
When I click on show more
Than I see more stuff
But I don't see show more anymore
```

With this understanding of specs I have come to see Discovery Sessions with clients to be more about trying to define all the events that should occur in the app and the main scenarios that go with these. 

I also think there are different types of events. UI events, time based events and processing events. In a way an event can be thought of as a function being run.

**Comment by danalexilewis** [comment]
Sorry that is a bit of a brain dump. @bhaugen @ahdinosaur @fosterlynn I'd be interested in your thoughts.

**Comment by bhaugen** [comment]
A bit of a brain dump in response, for starters. We're (me and @fosterlynn ) being asked to write some specs for a huge python/django app that was one of the precursors to Value Flows so a friend can rewrite parts of it in javascript. So I got to thinking about how would I write specs these days.

And then I was thinking I should really write the specs in terms of VF, not the old app.

And then, I ran into your comments about focusing yourself on specs instead of code. And you were doing it in terms of VF.

Wow!

So I'm mostly just following along and trying to learn.

A few comments:
- I'm missing an overview, which I guess would be the Domain Driven Design? I see the whiteboard jam 
  ![here](https://raw.githubusercontent.com/valueflows/resourceful/master/specification/assets/images/wb-jam-01.jpg)
  ...although the link in the readme still 404s. Where did you intend to go with the DDD? Are the VF concepts useful as part or all of the DDD? What's next?
  - Is the incompleteness a symptom of the current low priority of resourceful? (That's not a complaint, just wondering where it fits in your and @ahdinosaur 's schemes of life.)
- You wrote above, 
  `But doesn't make sense`
  but I couldn't figure out what didn't make sense.
- Picky comment: shdn't `Than` be `Then` in your example event definitions?

**Comment by danalexilewis** [comment]
@bhaugen the link in the readme goes to http://www.methodsandtools.com/archive/archive.php?id=97 is that giving you a 404?

Yes than should be then!.. story of my life.

`But doesn't make sense` sorry about that. that really doesn't make sense.

it was referring to the use of `But` statements in conditions. eg

```
Given I am an Anonymous User
But I do not have a shopping cart cookie
When I load any page
Than my cart is empty
```

as you could state it like this

```
Given I am an Anonymous User
When I load any page
Than my cart is empty
```

Lastly where am I going with DDD. Great question. In short I am looking to moving to replace user stories with ddd using gherkins - thus far my focus has been on trying to ignore the ui and thinking about the app at the api level. However this created to much cognitive dissonance for the clients. So instead I am looking to move to a much more open approach where 'ui' events are ok :)

So for resourceful the idea was to create a UI-less service that had a demo use case of an asset manager. As far as the plan goes - I have just been swamped of late... I hope to come back to this in the near future.

**Comment by danalexilewis** [comment]
also noting: I have been using the terminology of 
Conditions: all the Givens
Event: the When
Consequences: all the thens

**Comment by bhaugen** [comment]
> the link in the readme goes to http://www.methodsandtools.com/archive/archive.php?id=97 is that giving you a 404?

No, the link to the whiteboard jam image.
[edit to add]
this one 404s: https://github.com/valueflows/resourceful/blob/master/jams/wb-jam-01.JPG
and this one, too: https://github.com/valueflows/resourceful/blob/master/features

**Comment by bhaugen** [comment]
> thus far my focus has been on trying to ignore the ui and thinking about the app at the api level. However this created to much cognitive dissonance for the clients. So instead I am looking to move to a much more open approach where 'ui' events are ok :)

Since I am not a client, I like the UI-less api-level approach.

**Comment by danalexilewis** [comment]
Yep fair enough. I suppose I use client/user interchangeably, getting them to be able to think in a gherkin way is key to getting actionable feedback. 

I would still argue for an event based approach. In a sense each end point on an api is a place where async events occur. The other event type is the time activated events. Lastly I was also thinking that an event could be some sort of functional activity, processing a payment on a cron event has a listener/event that fires off a function to send a message somewhere.

This is all starting to sound very much how frameworks like @ahdinosaur inu work :) which is a good thing as it means that I am driving towards having a way of speccing that synergises well with it.

**Comment by bhaugen** [comment]
Did not understand

> This is all starting to sound very much how frameworks like @ahdinosaur inu work

Or how DDD relates to gherkins...

**Comment by danalexilewis** [comment]
For me:
DDD is the adopted cognitive approach for thinking about the problem/solution.
gherkins are format for documenting the proposed solution.

I have found that getting people writing gherkins is easier than getting people thinking in DDD. Even though that is exactly what they are doing some of the time. 

In regards to inu - I was referring to https://github.com/jarvisaoieong/redux-architecture#redux-architecture. I can see thinking in events when documenting spec is already thinking in a way that suits this architecture.

**Comment by bhaugen** [comment]
> I have found that getting people writing gherkins is easier than getting people thinking in DDD.

In my experience it depends on how they think. Some people start by trying to conceptualize, getting the general idea first. Some people start procedurally, wanting to know what to do first. Nothing wrong with either approach, they can either be complementary or the source of arguments and frustration.

P.S. I personally like to get at least some of the concepts first and then go into the details and procedures.

**Comment by danalexilewis** [comment]
So my hypothesis is:  whether a person thinks procedurally or conceptually does not matter as both can be documented in gherkin. It is about creating a common specific language between the users/client and the developers.

> I personally like to get at least some of the concepts first and then go into the details and procedures.

How do you currently document the details and procedures?

**Comment by bhaugen** [comment]
> How do you currently document the details and procedures?

All over the place, unfortunately. Often just in code. Hack it into submission. Sometimes tests before or after the code. Sometimes design discussion docs before the code. Sometimes explanations after the code. 

Here, for example, are a variety of attempts to explain a problem with a lot of necessary complexity, value equations: 
- [early design discussion](https://docs.google.com/document/d/1Bh0hhB_gqZD6p4fRfdnhqlCKwOJvLURgBttgcLp3er4/edit?usp=sharing). Lots more where that came from.
- [tests](https://github.com/valnet/valuenetwork/blob/master/valuenetwork/valueaccounting/tests/test_value_equations.py). Likewise.
- [algorithm explanation](https://docs.google.com/document/d/1hg0q7zNyuM1OM-8OOoZrkCPpB_EUH8YGLLnfoDFopy4/edit?usp=sharing).
- [code](https://github.com/valnet/valuenetwork/blob/master/valuenetwork/valueaccounting/models.py#L9462) (but you really don't want to read this...)
- [slide deck](https://speakerdeck.com/mikorizal/10-nrp-value-equation-concepts-and-tutorial)

How would you do something like that with gherkins?

**Comment by bhaugen** [comment]
Possibly relevant:
http://dret.typepad.com/dretblog/2016/08/api-maps-hypermedia-api-design.html

**Comment by danalexilewis** [comment]
@bhaugen that was a very interesting read.

extends upon the ideas i first came across here https://en.m.wikipedia.org/wiki/HATEOAS

or rather frames a design methodology for it.

At the moment I think a successful project needs three things before development.
1. Job stories - these are basically the ultimate documentation of the motivations/why it is this app/feature is to be built.
2. Gherkin/Cucumber Spec - testable acceptance criteria for the functional elements of the app/feature.
3. Wireframes - a ui spec indicating how things are meant to be.

I would say that a job can start with incomplete Ui and Functional specs, but needs a complete (or as complete as possible) job stories set.

Using an agile approach the UI and Functional spec can be extended/modified as you go. Specifically being extended as part of a sprint plan and reviewed as part of a review.

@ahdinosaur you were asking me about this the other day ^

**Comment by bhaugen** [comment]
> At the moment I think a successful project needs three things before development.

DDD?

**Comment by danalexilewis** [comment]
I am a huge fan of DDD, for me this is what no. 2 is all about. Designing the behaviors of the app using a specific language.
1. is more like a high level brief
2. is a visual representation of the same thing - modeling behaviors. 

I think there is a third hybrid option which is a mockapp. half code half visual. It can get you in front of peeps fast.

ps i like questions :) and this is all WIP at my end so take it all with a grain of salt - at least for now.

**Comment by bhaugen** [comment]
What do you think is the difference between DDD and a domain ontology?

To the extent that VF could be called a domain ontology, to what extent did you:
- find VF to be a useful starting point for DDD?
- need to extend or modify VF to create a useful DDD?

And do you think there is a diff between DDD and a gherkin spec?

(Gherkin seems more procedural to me. For a given domain ontology (VF) I can imagine, and I think we will see, lots of different apps that will have lots of different procedural specs. E.g Cobuy vs something like Sensorica.)

**Comment by bhaugen** [comment]
https://cucumber.io/blog/2015/12/08/example-mapping-introduction ?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/resourceful/-/issues/5.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
